name: CI Pipeline Nikita

on:
  push:
    branches:
      - Robot-master-nikita-ci
  pull_request:
    branches:
      - Robot-master-nikita-ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 

      - name: Checkout code